#define LINESENSOR_LEFT 22
#define LINESENSOR_RIGHT 24

#define ENCODERSENSOR_LEFT 3
#define ENCODERSENSOR_RIGHT 2

#define ULTRASONIC_FRONTUP_TRIG 37
#define ULTRASONIC_FRONTUP_ECHO 18
#define ULTRASONIC_FRONTDOWN_TRIG 52
#define ULTRASONIC_FRONTDOWN_ECHO 50
#define ULTRASONIC_LEFT_TRIG 53
#define ULTRASONIC_LEFT_ECHO 51
#define ULTRASONIC_RIGHT_TRIG 23
#define ULTRASONIC_RIGHT_ECHO 25

#define GIRO_SDA 20
#define GIRO_SCL 21

#define COLOR_F_S0 26
#define COLOR_F_S1 28
#define COLOR_F_S2 30
#define COLOR_F_S3 32
#define COLOR_F_OUT 34
#define COLOR_B_S0 48
#define COLOR_B_S1 46
#define COLOR_B_S2 42
#define COLOR_B_S3 40
#define COLOR_B_OUT 44

#define MOTOR_LEFT_PWM 6
#define MOTOR_LEFT_IN1 47
#define MOTOR_LEFT_IN2 49
#define MOTOR_RIGHT_PWM 9
#define MOTOR_RIGHT_IN1 39
#define MOTOR_RIGHT_IN2 41
#define MOTOR_INTAKE_PWM 5
#define MOTOR_INTAKE_IN1 43
#define MOTOR_INTAKE_IN2 45